---
version: '3.9'

networks:
    app_network:
        external: true
        name: ${APP_DOCKER_NETWORK}

volumes:
    redis_data:

services:

    redis:
        image: redis:7.0-alpine
        hostname: redis
        container_name: ${COMPOSE_PROJECT_NAME}_redis
        ports:
            - "${COMPOSE_REDIS_PORT:-6379}:6379"
        cap_add:
            - SYS_RESOURCE
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
            - redis_data:/data
        command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--bind", "0.0.0.0"]
        networks:
            app_network:
        healthcheck:
            test: ["CMD-SHELL", "redis-cli -a \"REDIS_PASSWORD\" --no-auth-warning ping | grep PONG"]
            start_period: 10s
            interval: 30s
            timeout: 5s
            retries: 3
