version: '3.9'

networks:
    app_network:
        driver: bridge
        name: ${APP_DOCKER_NETWORK}
        ipam:
            driver: default
            config:
                - subnet: 172.10.20.0/24

services:

    hello-world:
        image: hello-world:latest
        hostname: hello-world
        container_name: ${COMPOSE_PROJECT_NAME}-${CONTAINER_VERSION}_hello-world
        networks:
            app_network:
