---
version: '3.9'

networks:
    app_network:
        external: true
        name: ${APP_DOCKER_NETWORK}

services:

    webserver:
        image: nginx:stable-alpine
        hostname: webserver
        container_name: ${COMPOSE_PROJECT_NAME}_webserver
        ports:
            - target: 80
              published: ${WEBSERVER_PORT_HTTP:-8012}
              protocol: tcp
              mode: host
        volumes:
            - ./public:${REMOTE_SRC}/public
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            app_network:
        # Graceful shutdown
        stop_grace_period: 30s
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"
                mode: "non-blocking"
                tag: "logging-webserver"
