---
version: '3.9'

networks:
    app_network:
        external: true
        name: ${APP_DOCKER_NETWORK}

volumes:
    mysql_data:

services:

    database:
        image: mysql:8.0
        hostname: mysql
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        ports:
            - "${COMPOSE_MYSQL_PORT:-3306}:3306"
        volumes:
            - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
            - mysql_data:/var/lib/mysql
        env_file:
            - .env
        networks:
            app_network:
        # Graceful shutdown
        stop_grace_period: 30s
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"
                mode: "non-blocking"
                tag: "logging-mysql"
        healthcheck:
            test: export MYSQL_PWD="Pa55w0rd"; output=$$(mysqladmin ping --port=3306 --user=$$MYSQL_USER 2>&1); echo $$output | grep 'mysqld is alive' || { echo $$output; exit 1; }
            start_period: 10s
            interval: 30s
            timeout: 5s
            retries: 3
